import os
import csv
import time
from datetime import datetime

base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
output_dir = os.path.join(base_dir, "data", "output")
reports_dir = os.path.join(base_dir, "output", "reports")

FILES_TO_CHECK = [
    "data/output/web_tasting_note_real_source_candidates.csv",
    "data/output/web_tasting_note_snapshots.csv",
    "data/output/web_tasting_note_snapshots_index.csv",
    "data/output/web_tasting_note_extraction_preview.csv",
    "data/output/web_tasting_note_staging_preview.csv",
    "data/output/real_web_tasting_note_source_candidates.csv",
    "data/output/real_web_tasting_note_snapshots.csv",
    "data/output/real_web_tasting_note_extraction_preview.csv",
    "data/output/real_web_tasting_note_staging_candidates.csv",
    "data/output/real_web_tasting_note_rejected.csv",
    "data/output/real_web_tasting_note_manual_review.csv",
    "output/reports/269_real_web_tasting_note_pipeline_report.md",
    "output/reports/270_12p_real_web_tasting_note_pipeline_gate.txt"
]

def count_csv(path):
    if not os.path.exists(path): return 0
    with open(path, 'r', encoding='utf-8') as f:
        return sum(1 for row in csv.DictReader(f))

def main():
    report_269 = os.path.join(base_dir, "output/reports/269_real_web_tasting_note_pipeline_report.md")
    baseline_time = 0
    if os.path.exists(report_269):
        baseline_time = os.path.getmtime(report_269)
    else:
        baseline_time = time.time() # fallback
        
    audit_data = []
    
    stale_files = []
    current_files = []
    missing_files = []
    
    staging_file_path = "data/output/web_tasting_note_staging_preview.csv"
    extraction_file_path = "data/output/web_tasting_note_extraction_preview.csv"
    
    extraction_preview_count = 0
    staging_candidate_count = 0
    is_staging_stale = False
    
    for f_rel in FILES_TO_CHECK:
        f_abs = os.path.join(base_dir, f_rel)
        exists = os.path.exists(f_abs)
        row_count = 0
        mod_time_str = "N/A"
        stale_or_current = "N/A"
        
        if exists:
            mod_time = os.path.getmtime(f_abs)
            mod_time_str = datetime.fromtimestamp(mod_time).isoformat()
            
            if f_rel.endswith('.csv'):
                row_count = count_csv(f_abs)
                
            # If older than 10 minutes from baseline, it's stale
            if (baseline_time - mod_time) > 600:
                stale_or_current = "STALE"
                stale_files.append(f_rel)
            else:
                stale_or_current = "CURRENT"
                current_files.append(f_rel)
                
            if f_rel == staging_file_path:
                staging_candidate_count = row_count
                if stale_or_current == "STALE":
                    is_staging_stale = True
            if f_rel == extraction_file_path:
                extraction_preview_count = row_count
                
        else:
            missing_files.append(f_rel)
            
        audit_data.append({
            'path': f_rel,
            'exists': exists,
            'modified_time': mod_time_str,
            'row_count': row_count,
            'expected_lineage': '12P-REAL',
            'stale_or_current': stale_or_current
        })
        
    # Write CSV
    audit_csv = os.path.join(output_dir, "real_web_tasting_note_lineage_audit.csv")
    with open(audit_csv, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=['path', 'exists', 'modified_time', 'row_count', 'expected_lineage', 'stale_or_current'])
        writer.writeheader()
        writer.writerows(audit_data)
        
    # Write Report
    report_md = os.path.join(reports_dir, "271_12p_real_web_pipeline_lineage_audit_report.md")
    with open(report_md, 'w', encoding='utf-8') as f:
        f.write("# 12P-REAL Web Pipeline Lineage Audit Report\n\n")
        f.write("""\nEstimated API Cost: $0.00\nActual API Cost: $0.00\nLocal Compute Used: Yes\nFully Local Execution: Yes\n""")

        f.write("## 1. Discrepancy Investigation\n")
        f.write(f"- Extraction Preview Count: {extraction_preview_count}\n")
        f.write(f"- Staging Candidate Count: {staging_candidate_count}\n")
        f.write(f"- Is Staging Candidate File Stale?: {'YES' if is_staging_stale else 'NO'}\n\n")
        
        f.write("## 2. Explanation\n")
        if is_staging_stale:
            f.write("The file `web_tasting_note_staging_preview.csv` is STALE. It was not generated by the 12P-REAL run. The prepare script might have failed or skipped execution due to the empty output of the previous step, leaving the old 19 rows from a previous run.\n")
        elif extraction_preview_count == 2 and staging_candidate_count == 19:
            f.write("The file `web_tasting_note_staging_preview.csv` is CURRENT. The prepare script appends to the file or the `web_tasting_note_staging_preview.csv` actually contained more rows due to how the script merges data. We need to inspect the `prepare_tasting_note_staging_preview.py` logic to be sure.\n")
        else:
            f.write("The discrepancy may have been resolved or the counts are different now.\n")
            
        f.write("\n## 3. File Lineage Summary\n")
        f.write("### CURRENT Files (from 12P-REAL)\n")
        for x in current_files: f.write(f"- {x}\n")
        f.write("\n### STALE Files (from old runs)\n")
        for x in stale_files: f.write(f"- {x}\n")
        f.write("\n### MISSING Files\n")
        for x in missing_files: f.write(f"- {x}\n")
        
    # Write Gate
    gate_txt = os.path.join(reports_dir, "272_12p_real_web_pipeline_lineage_gate.txt")
    gate = "GO"
    if is_staging_stale and staging_candidate_count == 19:
        gate = "NO-GO_STALE_OUTPUT"
        
    with open(gate_txt, 'w', encoding='utf-8') as f:
        f.write(f"GATE: {gate}\n")
        if gate == "NO-GO_STALE_OUTPUT":
            f.write("REASON: staging_candidate_count is 19 but the file is STALE (from an old run).\n")
        else:
            f.write("All lineage checks passed. Stale output is not the cause, or counts are consistent.\n")

if __name__ == "__main__":
    main()
