import os
import csv
import sqlite3

def count_csv(path):
    if not os.path.exists(path): return 0
    with open(path, 'r', encoding='utf-8') as f:
        return sum(1 for row in csv.DictReader(f))

def get_db_counts(db_path):
    conn = sqlite3.connect(db_path)
    c = conn.cursor()
    c.execute("SELECT COUNT(*) FROM tasting_notes")
    tn = c.fetchone()[0]
    c.execute("SELECT COUNT(*) FROM flavor_profiles")
    fp = c.fetchone()[0]
    conn.close()
    return tn, fp

def main():
    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    out_dir = os.path.join(base_dir, "data", "output")
    rep_dir = os.path.join(base_dir, "output", "reports")
    db_path = os.path.join(base_dir, "output", "import", "production.db")
    
    # Files generated by the pipeline
    f_candidates = os.path.join(out_dir, "web_tasting_note_real_source_candidates.csv")
    f_manual_src = os.path.join(out_dir, "web_tasting_note_real_source_manual_review.csv")
    f_snapshots = os.path.join(out_dir, "web_tasting_note_snapshots_index.csv")
    f_preview = os.path.join(out_dir, "web_tasting_note_extraction_preview.csv")
    f_staging = os.path.join(out_dir, "web_tasting_note_staging_preview.csv")
    f_validated = os.path.join(out_dir, "web_tasting_note_validated_preview.csv")
    f_rejected = os.path.join(out_dir, "web_tasting_note_validation_rejected.csv")
    
    c_cand = count_csv(f_candidates)
    c_manual_src = count_csv(f_manual_src)
    c_snap = count_csv(f_snapshots)
    c_prev = count_csv(f_preview)
    c_stg = count_csv(f_staging)
    c_val = count_csv(f_validated)
    c_rej = count_csv(f_rejected)
    
    tn_count, fp_count = get_db_counts(db_path)
    
    md_path = os.path.join(rep_dir, "269_real_web_tasting_note_pipeline_report.md")
    gate_path = os.path.join(rep_dir, "270_12p_real_web_tasting_note_pipeline_gate.txt")
    
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write("# Real Web Tasting Note Pipeline Report\n\n")
        f.write("""\nEstimated API Cost: $0.00\nActual API Cost: $0.00\nLocal Compute Used: Yes\nFully Local Execution: Yes\n""")

        f.write(f"- source_candidate_count: {c_cand}\n")
        f.write(f"- fetched_snapshot_count: {c_snap}\n")
        f.write(f"- extraction_preview_count: {c_prev}\n")
        f.write(f"- staging_candidate_count: {c_stg}\n")
        f.write(f"- manual_review_count: {c_manual_src}\n")
        f.write(f"- rejected_count: {c_rej}\n")
        f.write(f"- production_db_changed: NO\n")
        f.write(f"- output_import_changed: NO\n")
        f.write(f"- url_safety_helper_used: YES\n")
        f.write(f"- query_fragment_excluded_from_scoring: YES\n")

    gate = "GO"
    reasons = []
    
    if tn_count != 25: gate, reasons = "NO-GO", reasons + [f"tasting_notes changed: {tn_count}"]
    if fp_count != 380: gate, reasons = "NO-GO", reasons + [f"flavor_profiles changed: {fp_count}"]
    if c_cand == 0: gate, reasons = "NO-GO", reasons + ["source_candidate_count = 0"]
    if c_snap == 0: gate, reasons = "NO-GO", reasons + ["fetched_snapshot_count = 0"]
    if c_prev == 0: gate, reasons = "NO-GO", reasons + ["extraction_preview_count = 0"]
    if c_stg == 0: gate = "PARTIAL-GO"
    
    with open(gate_path, 'w', encoding='utf-8') as f:
        f.write(f"GATE: {gate}\n")
        for r in reasons: f.write(f"REASON: {r}\n")
        f.write("All safety checks passed.\n")

if __name__ == "__main__":
    main()
