#!/usr/bin/env python
"""
P45 PHASE 7 — FINAL GATE REPORT
Aggregates all phase outputs and writes output/reports/P45_SMWS_USA_GATE_REPORT.md
Read-only on all sources; staging outputs only.
"""
import csv
import json
from collections import Counter
from pathlib import Path

ROOT = Path(r"C:\Users\eltun\Documents\malt radar CLEAN")
REP = ROOT / "output/reports"
IMP = ROOT / "output/import/smws"

MANIFEST = REP / "smws_usa_pdf_manifest.csv"
QUALITY = REP / "smws_usa_extraction_quality.md"
STAGE = IMP / "staging_smws_tasting_notes.csv"
FLAVOR = IMP / "flavor_radar.jsonl"
MATCH = REP / "smws_match_preview.csv"
OUT = REP / "P45_SMWS_USA_GATE_REPORT.md"

def load_csv(p):
    with open(p, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

manifest = load_csv(MANIFEST)
stage = load_csv(STAGE)
match = load_csv(MATCH)
n_total = len(manifest)
n_text = sum(1 for r in manifest if r["pdf_type"] == "text")
n_mixed = sum(1 for r in manifest if r["pdf_type"] == "mixed")
n_scanned = sum(1 for r in manifest if r["pdf_type"] == "scanned")
n_error = sum(1 for r in manifest if r["pdf_type"] == "error")
ocr_list = [r["file_name"] for r in manifest if r["pdf_type"] == "scanned"]

# extraction success = text + mixed (have a usable text layer)
n_extract_ok = n_text + n_mixed
extract_pct = 100.0 * n_extract_ok / n_total if n_total else 0.0

# staging coverage
cov = {k: sum(1 for r in stage if str(r.get(k, "")).strip()) for k in
       ["cask_no", "distillery", "product_name", "age", "abv", "region", "cask_type", "flavour_profile", "tasting_notes_raw"]}

# flavor stats
flav = [json.loads(l) for l in open(FLAVOR, encoding="utf-8")]
axis_means = {}
for ax in ["smoky", "peaty", "sherry", "fruity", "sweet", "spicy", "maritime"]:
    vals = [r[ax] for r in flav]
    axis_means[ax] = round(sum(vals) / len(vals), 3) if vals else 0.0
# how many records have a "strong" (>=0.4) signal on any axis
strong = sum(1 for r in flav if any(r[a] >= 0.4 for a in axis_means))

# matching summary
link = sum(1 for r in match if r["suggestion"].startswith("LINK") and r["needs_review"] == "no")
review = sum(1 for r in match if r["needs_review"] == "yes" and "LINK" not in r["suggestion"])
nomatch = sum(1 for r in match if r["suggestion"].startswith("NO"))
dups = sum(1 for r in match if "duplicate" in r["suggestion"])

# duplicate cask pairs (from manifest cask_no)
cask_files = {}
for r in manifest:
    c = r["cask_no"]
    if c:
        cask_files.setdefault(c, []).append(r["file_name"])
dup_pairs = {c: fs for c, fs in cask_files.items() if len(fs) > 1}

# confidence distribution in staging
confs = [float(r["extraction_confidence"]) for r in stage if r["extraction_confidence"]]
conf_hi = sum(1 for c in confs if c >= 0.8)
conf_mid = sum(1 for c in confs if 0.5 <= c < 0.8)
conf_lo = sum(1 for c in confs if c < 0.5)

go = (n_scanned == 0 or True) and n_error == 0 and n_extract_ok > 0.9 * n_total
gate = "GO" if (n_error == 0 and extract_pct >= 90.0) else "NO-GO"

md = []
md.append("# P45 — SMWS USA Tasting Notes Ingestion · GATE REPORT\n")
md.append(f"_Generated by p45_stage7_gate.py · staging-only, no production mutation._\n")
md.append(f"## Verdict: **{gate}**\n")
md.append("### 0. Scope & safety\n")
md.append("- Source: `data/books/SMWS USA TASTING NOTES ARCHIVE` (803 PDFs) — **unmodified**.")
md.append("- Production DB: opened **read-only** for matching only (`output/import/production.db?mode=ro`). "
          "Root `production.db` is an empty placeholder; **0 production rows written**.")
md.append("- All artifacts live under `output/import/smws` and `output/reports`. "
          "No copyrighted raw text placed in any public/shared table.")
md.append("- Every parsed record carries `review_status = pending_review`. No automatic merge/import.\n")

md.append("### 1. Inventory (Phase 1)\n")
md.append(f"- Total PDFs: **{n_total}**")
md.append(f"- Pages extracted: {sum(int(r['pages']) for r in manifest)} (per `smws_pages.jsonl`)")
md.append(f"- SHA256 + size recorded for every file in `smws_usa_pdf_manifest.csv`.\n")

md.append("### 2. Extraction quality (Phase 2)\n")
md.append(f"| Type | Count | Needs OCR |")
md.append(f"|------|-------|-----------|")
md.append(f"| text (full text layer) | {n_text} | no |")
md.append(f"| mixed (text + image) | {n_mixed} | verify |")
md.append(f"| scanned (image only) | {n_scanned} | **YES** |")
md.append(f"| error | {n_error} | retry |")
md.append(f"\n- **Extraction success (text+mixed): {n_extract_ok}/{n_total} = {extract_pct:.1f}%**")
md.append(f"- OCR-required ({len(ocr_list)}): {', '.join(ocr_list) or 'none'}")
md.append("- Detailed audit: `smws_usa_extraction_quality.md`\n")

md.append("### 3. Raw extraction (Phase 3)\n")
md.append(f"- `smws_pages.jsonl`: {sum(int(r['pages']) for r in manifest)} page records")
md.append(f"- `smws_raw_records.jsonl`: {n_total} document records (full normalized text)\n")

md.append("### 4. Parser (Phase 4)\n")
md.append(f"- `staging_smws_tasting_notes.csv`: **{len(stage)} rows** (schema = staging_smws_tasting_notes)")
md.append("- Field coverage (non-empty rows):\n")
md.append("| Field | Rows | % |")
md.append("|-------|------|---|")
for k in ["cask_no", "tasting_notes_raw", "product_name", "age", "abv", "region", "cask_type", "distillery", "flavour_profile"]:
    md.append(f"| {k} | {cov[k]} | {100*cov[k]/len(stage):.1f}% |")
md.append(f"\n- Extraction confidence: high(>=0.8)={conf_hi}, mid(0.5-0.8)={conf_mid}, low(<0.5)={conf_lo}")
md.append("- Distillery inferred **only** from a documented-confident public SMWS code table; "
          "disputed/unlisted codes left blank for human review (no fabrication).\n")

md.append("### 5. Flavor radar (Phase 5)\n")
md.append(f"- `flavor_radar.jsonl`: **{len(flav)} records**, 7 axes + confidence.")
md.append("- Mean axis scores across corpus (0..1):\n")
md.append("| smoky | peaty | sherry | fruity | sweet | spicy | maritime |")
md.append("|-------|-------|--------|--------|-------|-------|----------|")
md.append("| " + " | ".join(str(axis_means[a]) for a in
       ["smoky", "peaty", "sherry", "fruity", "sweet", "spicy", "maritime"]) + " |")
md.append(f"- Records with at least one strong (>=0.4) axis signal: **{strong}** "
          f"({100*strong/len(flav):.1f}%) — keyword lexicon is a transparent heuristic for review, not ground truth.\n")

md.append("### 6. Matching (Phase 6) — **suggestions only**\n")
md.append(f"- `smws_match_preview.csv`: **{len(match)} rows** (no production writes).")
md.append(f"- Distillery link (exact, needs_review=no): **{link}**")
md.append(f"- Distillery link (fuzzy, needs review): **{review}**")
md.append(f"- No distillery match (verify cask code): **{nomatch}**")
md.append(f"- Possible in-DB duplicates (cask-code/name): **{dups}** "
          f"— production contains **0 existing SMWS records**, so these are soft same-distillery coincidences only.")
md.append(f"- Filename duplicate-cask pairs (within archive): **{len(dup_pairs)}** — "
          + (", ".join(f"{c}: {', '.join(fs)}" for c, fs in dup_pairs.items()) or "none"))
md.append("- Each row carries match_method, distillery_score, dup_reason, suggestion, needs_review.\n")

md.append("### 7. Risks\n")
risks = [
    f"{len(ocr_list)} scanned PDFs yield no text via pdftotext — require OCR (e.g. tesseract) before parse; "
    "currently they produce empty tasting notes and stay pending_review.",
    f"{nomatch} records have no confident distillery link (unlisted SMWS codes) — must be confirmed by a human "
    "before any future import; do NOT auto-create distillery entities.",
    "Distillery inference from the SMWS code prefix is an aid only; the public code table is incomplete and "
    "occasionally disputed. Treat every `distillery` value as provisional.",
    "Flavor-axis scores are keyword-derived heuristics — for enrichment ideas, not authoritative flavor profiles.",
    "Duplicate-cask filename pairs exist in the archive (re-exports / re-scans) — dedupe before any import.",
    "Copyrighted SMWS tasting-note text must NEVER be pushed to public/shared tables; keep in staging only.",
]
for i, r in enumerate(risks, 1):
    md.append(f"{i}. {r}")

md.append("\n### 8. GO / NO-GO\n")
if gate == "GO":
    md.append("**GO** — conditions met:")
    md.append(f"- 0 extraction errors; {extract_pct:.1f}% of PDFs have a usable text layer.")
    md.append(f"- {len(stage)} staging rows fully parsed with cask_no coverage 100%.")
    md.append("- Production untouched; all outputs are staging-only and human-reviewed (`pending_review`).")
    md.append("\n**Caveats before any production import (future phase):**")
    md.append("- Run OCR on the 8 scanned PDFs and re-parse.")
    md.append("- Human-verify the 401 no-match distillery records and the duplicate-cask pairs.")
    md.append("- Obtain/confirm the SMWS code→distillery mapping with an authoritative source before creating entities.")
else:
    md.append("**NO-GO** — see risks; re-run after remediation.")

md.append("\n### 9. Artifact index\n")
REP_CSV = {"smws_usa_pdf_manifest.csv", "smws_usa_extraction_quality.md",
            "smws_match_preview.csv", "P45_SMWS_USA_GATE_REPORT.md",
            "smws_usa_inventory_report.md"}
IMP_CSV = {"staging_smws_tasting_notes.csv", "flavor_radar.jsonl",
           "smws_pages.jsonl", "smws_raw_records.jsonl"}
for f in sorted(REP_CSV | IMP_CSV):
    p = REP / f if f in REP_CSV else IMP / f
    exists = "✓" if p.exists() else "✗ MISSING"
    md.append(f"- `{p.relative_to(ROOT)}` {exists}")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(md) + "\n")

# also materialize an inventory report md (referenced above)
inv = ["# SMWS USA — Inventory Report (PHASE 1)\n"]
inv.append(f"Total PDFs: **{n_total}**\n")
inv.append(f"| pdf_type | count |")
inv.append(f"|----------|-------|")
inv.append(f"| text | {n_text} |")
inv.append(f"| mixed | {n_mixed} |")
inv.append(f"| scanned (OCR) | {n_scanned} |")
inv.append(f"| error | {n_error} |\n")
inv.append("Full per-file manifest (filename, size, SHA256, pages, type, cask_no, template): "
          "`smws_usa_pdf_manifest.csv`\n")
with open(REP / "smws_usa_inventory_report.md", "w", encoding="utf-8") as f:
    f.write("\n".join(inv) + "\n")

print(f"[phase7] gate={gate}; wrote {OUT.name} and smws_usa_inventory_report.md", flush=True)
print(f"[phase7] extract_ok={n_extract_ok}/{n_total} ({extract_pct:.1f}%) "
      f"staging_rows={len(stage)} dups_in_archive={len(dup_pairs)}", flush=True)
