#!/usr/bin/env python
"""
P45 SMWS USA TASTING NOTES — PHASE 1 (inventory) + PHASE 3 (raw extraction)

Strict rules honoured:
- Read-only on source PDFs and on production DB.
- No production mutation.
- All outputs under output/ (staging).
- PDF raw text kept ONLY in staging output files, never written to public tables.

Outputs:
  output/reports/smws_usa_pdf_manifest.csv
  output/import/smws/smws_pages.jsonl
  output/import/smws/smws_raw_records.jsonl
  (inventory markdown report is generated by a separate step using the manifest)
"""
import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(r"C:\Users\eltun\Documents\malt radar CLEAN")
SRC = ROOT / "data/books/SMWS USA TASTING NOTES ARCHIVE"
OUT_REPORTS = ROOT / "output/reports"
OUT_IMPORT = ROOT / "output/import/smws"
OUT_REPORTS.mkdir(parents=True, exist_ok=True)
OUT_IMPORT.mkdir(parents=True, exist_ok=True)

PDFTEXT = "pdftotext"  # poppler in PATH

def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()

def page_count(path: Path) -> int:
    # use pdftotext -f/-l trick? Use a cheap method: pdftotext -> count form-feeds,
    # but better: poppler has no pdfinfo. We count "\f" (page breaks) in extracted text.
    return None  # filled later from extraction

def extract_pages(path: Path):
    """Return list of per-page text blocks using pdftotext -layout."""
    try:
        proc = subprocess.run(
            [PDFTEXT, "-layout", str(path), "-"],
            capture_output=True, timeout=120,
        )
        # pdftotext can emit non-UTF8 bytes; decode defensively
        text = proc.stdout.decode("utf-8", "replace")
    except Exception as e:
        return None, str(e)
    # pdftotext inserts a form-feed \f between pages
    raw_pages = text.split("\f")
    # normalize line endings, strip trailing whitespace per line, collapse blank lines lightly
    pages = []
    for p in raw_pages:
        # normalize unicode mojibake-ish control chars but keep text
        norm = p.replace("\r\n", "\n").replace("\r", "\n")
        pages.append(norm)
    return pages, None

# ---------- classification ----------
# A PDF is TEXT if layout extraction yields meaningful non-whitespace text across pages.
# A PDF is SCANNED if extraction yields almost nothing (image-only).
# MIXED if some pages have text and some do not.
def classify(pages):
    if pages is None:
        return "error", 0.0
    total_chars = 0
    pages_with_text = 0
    for p in pages:
        c = len(p.strip())
        total_chars += c
        if c > 40:  # non-trivial text on the page
            pages_with_text += 1
    n = len(pages) or 1
    ratio = pages_with_text / n
    dens = total_chars / (n * 1.0)
    if pages_with_text == 0:
        return "scanned", round(ratio, 3)
    if ratio >= 0.8:
        return "text", round(ratio, 3)
    return "mixed", round(ratio, 3)

# Field-detection probes used in PHASE 2 audit + PHASE 4 parser
CASK_RE = re.compile(r"CASK\s*(?:No\.?|#)\s*([0-9]{1,3}\.[0-9]{1,4})", re.IGNORECASE)
CASK_RE2 = re.compile(r"\b([0-9]{1,3}\.[0-9]{1,4})\b")  # fallback within CASK context
YO_RE = re.compile(r"(\d{1,3})\s*(?:YEARS|YEAR|YO\b)", re.IGNORECASE)
ABV_RE = re.compile(r"(\d{2,3}\.\d{1,2})\s*%", re.IGNORECASE)
REGION_TOKENS = ["SPEYSIDE", "HIGHLAND", "ISLAY", "CAMPBELTOWN", "LOWLAND", "ISLANDS",
                 "SPEY", "SPEYSIDE SPEY"]

def detect_fields(text):
    cask = CASK_RE.search(text)
    abvs = ABV_RE.findall(text)
    abv = None
    if abvs:
        # choose the ABV near the bottom line (last occurrence typically)
        abv = abvs[-1]
    years = YO_RE.search(text)
    age = years.group(1) if years else None
    region = None
    up = text.upper()
    for tok in REGION_TOKENS:
        if tok in up:
            region = tok.title()
            break
    has_flavor = bool(re.search(r"SPICY|SWEET|DRY|SMOKY|FRUITY|MALTLY|WOODY|LIGHT|OILY", up))
    return {
        "cask_no": cask.group(1) if cask else None,
        "abv": abv,
        "age": age,
        "region": region,
        "has_flavor_profile": has_flavor,
    }

def main():
    pdfs = sorted(SRC.rglob("*.pdf"), key=lambda p: p.name.lower())
    print(f"[phase1] found {len(pdfs)} PDFs", flush=True)

    manifest_rows = []
    pages_out = OUT_IMPORT / "smws_pages.jsonl"
    records_out = OUT_IMPORT / "smws_raw_records.jsonl"

    total_text = total_scanned = total_mixed = total_error = 0
    cask_found = 0

    with open(pages_out, "w", encoding="utf-8") as pf, \
         open(records_out, "w", encoding="utf-8") as rf:
        for i, p in enumerate(pdfs, 1):
            rel = p.relative_to(SRC)
            size = p.stat().st_size
            digest = sha256_of(p)
            pages, err = extract_pages(p)
            if pages is None:
                ptype = "error"
                total_error += 1
                ratio = 0.0
                fcount = 0
                # still emit a placeholder page record so audit sees the failure
                pf.write(json.dumps({
                    "source": "SMWS USA",
                    "file_name": p.name,
                    "page_number": 0,
                    "raw_text": "",
                    "extraction_method": "failed",
                    "error": err,
                }, ensure_ascii=False) + "\n")
                manifest_rows.append({
                    "file_name": p.name, "relative_path": str(rel), "size_bytes": size,
                    "sha256": digest, "pages": 0, "pdf_type": ptype,
                    "text_ratio": 0.0, "cask_no": "", "abv": "", "age": "",
                    "region": "", "extraction_ok": "false", "error": err or "",
                })
                rf.write(json.dumps({
                    "source": "SMWS USA", "file_name": p.name, "page_number": 0,
                    "raw_text": "", "extraction_method": "failed",
                }, ensure_ascii=False) + "\n")
                continue

            fcount = len(pages)
            ptype, ratio = classify(pages)
            if ptype == "text":
                total_text += 1
            elif ptype == "scanned":
                total_scanned += 1
            elif ptype == "mixed":
                total_mixed += 1

            full_text = "\n".join(pages)
            fields = detect_fields(full_text)
            if fields["cask_no"]:
                cask_found += 1

            method = "pdf_text" if ptype in ("text", "mixed") else "ocr"

            # per-page records
            for pi, pg in enumerate(pages, 1):
                pf.write(json.dumps({
                    "source": "SMWS USA",
                    "file_name": p.name,
                    "page_number": pi,
                    "raw_text": pg,
                    "extraction_method": method,
                }, ensure_ascii=False) + "\n")

            # per-document consolidated record (raw_text = full doc text)
            rf.write(json.dumps({
                "source": "SMWS USA",
                "file_name": p.name,
                "page_number": fcount,  # page count
                "raw_text": full_text,
                "extraction_method": method,
            }, ensure_ascii=False) + "\n")

            manifest_rows.append({
                "file_name": p.name, "relative_path": str(rel), "size_bytes": size,
                "sha256": digest, "pages": fcount, "pdf_type": ptype,
                "text_ratio": ratio, "cask_no": fields["cask_no"] or "",
                "abv": fields["abv"] or "", "age": fields["age"] or "",
                "region": fields["region"] or "", "extraction_ok": "true", "error": "",
            })

            if i % 100 == 0:
                print(f"[phase1] processed {i}/{len(pdfs)}", flush=True)

    # write manifest csv
    cols = ["file_name", "relative_path", "size_bytes", "sha256", "pages",
            "pdf_type", "text_ratio", "cask_no", "abv", "age", "region",
            "extraction_ok", "error"]
    import csv
    with open(OUT_REPORTS / "smws_usa_pdf_manifest.csv", "w", newline="", encoding="utf-8") as cf:
        w = csv.DictWriter(cf, fieldnames=cols)
        w.writeheader()
        for r in manifest_rows:
            w.writerow(r)

    summary = {
        "total_pdfs": len(pdfs),
        "text": total_text,
        "scanned": total_scanned,
        "mixed": total_mixed,
        "error": total_error,
        "cask_detected": cask_found,
        "pages_records": sum(1 for _ in open(pages_out, encoding="utf-8")),
        "raw_records": sum(1 for _ in open(records_out, encoding="utf-8")),
    }
    print("[phase1] DONE", json.dumps(summary), flush=True)
    with open(OUT_IMPORT / "_phase1_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

if __name__ == "__main__":
    main()
