# scripts/p54_schema_modernization.py
"""
P54 - Safe Schema Modernization (IMPLEMENTATION phase, generate-only).

Reads: AGENTS.md, memory/*, schema findings from P53, live schema inventory.
Writes (deterministic, evidence-backed, NO execution):
  output/migrations/p54_go_migration.sql        # changes that pass ALL 6 gates
  output/migrations/p54_blocked_reference.sql   # SQL/approach for BLOCKED items (do NOT run)
  output/reports/p54_migration_preview.sql      # human-readable preview = go_migration.sql
  output/reports/p54_schema_plan.md
  output/reports/p54_blocked_changes.md

This script NEVER opens production.db and NEVER runs any SQL.
It only writes migration files from embedded, evidence-backed SQL constants.

Gates (from task): a change is GO only if it satisfies ALL of
  1 no production risk   2 no Flutter breakage   3 no FastAPI breakage
  4 no Drift breakage     5 fully reversible      6 covered by migration SQL
Otherwise -> BLOCKED.

Evidence basis (queries run during analysis against output/import/production.db):
  SELECT COUNT(*), COUNT(DISTINCT whisky_id), SUM(whisky_id IS NULL)
    FROM whiskies;            -- 3293, 3293, 0  (whisky_id is a clean TEXT key)
  PRAGMA foreign_key_check;   -- 'foreign key mismatch - price_history referencing whiskies'
  SELECT COUNT(*) FROM whiskies WHERE typeof(abv)='text';  -- 1314 (all end with '%')
  SELECT COUNT(*) FROM whiskies WHERE typeof(abv)='real';   -- 18
  SELECT COUNT(*) FROM whiskies WHERE abv<0 OR abv>100;     -- 1314 (textual, post-fix -> 0)
  -- distilleries REAL-typed text cols (owner, founded_year, ...): ALL NULL (0 non-null)
  -- tasting_notes REAL-typed cols: source_url=109, source_name=77, notes_for_review=1461 TEXT (non-null)
  -- link tables (bottler_product_links, distillery_company_links, whisky_product_entities): 0 rows
  -- Drift DB (frontend) is a SEPARATE schema (malt_radar_v2, v6); does not read production.db tables.
  -- FastAPI reads whiskies/distilleries/tasting_notes/flavor_profiles/price_history by TEXT keys.
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MIG_DIR = os.path.join(ROOT, "output", "migrations")
REP_DIR = os.path.join(ROOT, "output", "reports")
os.makedirs(MIG_DIR, exist_ok=True)
os.makedirs(REP_DIR, exist_ok=True)

# ---------------------------------------------------------------------------
# GO migration: only changes that pass ALL 6 gates.
# Bundle into ONE transaction for atomicity + rollback safety.
# ---------------------------------------------------------------------------
GO_MIGRATION = """-- ============================================================================
-- P54 GO MIGRATION  (generated by scripts/p54_schema_modernization.py)
-- DO NOT EXECUTE AUTOMATICALLY. Apply on a verified staging copy of production.db,
-- inside the transaction below, then assert the post-conditions.
--
-- Scope (GO items only):
--   G-A: ABV type normalization (verified in P53)        -> UPDATE, reversible
--   G-B: Missing indexes on hot join/lookup columns      -> CREATE INDEX, reversible
--
-- NOT included (see p54_blocked_changes.md):
--   whisky_id PRIMARY KEY (requires full table rebuild -> BLOCKED, own gated migration)
--   distilleries/tasting_notes column-type rebuilds     -> BLOCKED (latent, no prod risk now)
--   link-table id-type mismatch                          -> BLOCKED (needs id-strategy decision)
--   price_history removal                                -> BLOCKED (P53: live data + live code)
-- ============================================================================

-- 0) Guard: ensure we are on the populated, expected DB shape.
PRAGMA foreign_keys = OFF;   -- table has no enforced FKs we mutate here

-- 1) PRE-CONDITIONS (assert before applying)
PRAGMA integrity_check;                                       -- expected: ok
SELECT COUNT(*) FROM whiskies WHERE typeof(abv)='text';      -- expected: 1314
SELECT COUNT(*) FROM whiskies WHERE abv<0 OR abv>100;        -- expected: 1314
SELECT COUNT(*) FROM whiskies WHERE typeof(abv)='real';      -- expected: 18

-- 2) APPLY (single transaction)
BEGIN IMMEDIATE;

  -- G-A: normalize ABV text+% -> REAL percentage.
  -- Correct transform is STRIP('%') + CAST (NOT divide by 100).
  -- WHERE isolates only the 1314 bad rows; the 18 valid REAL rows and 1961 NULLs untouched.
  UPDATE whiskies
     SET abv = CAST(REPLACE(REPLACE(abv, ',', '.'), '%', '') AS REAL)
   WHERE typeof(abv) = 'text'
     AND abv LIKE '%';

  -- G-B: indexes on hot columns. Safe, query-plan only, no semantic change.
  CREATE INDEX IF NOT EXISTS idx_whiskies_distillery_id ON whiskies(distillery_id);
  CREATE INDEX IF NOT EXISTS idx_whiskies_name          ON whiskies(name);
  CREATE INDEX IF NOT EXISTS idx_whiskies_country       ON whiskies(country);
  CREATE INDEX IF NOT EXISTS idx_tasting_notes_whisky_id ON tasting_notes(whisky_id);
  CREATE INDEX IF NOT EXISTS idx_flavor_profiles_whisky_id ON flavor_profiles(whisky_id);
  CREATE INDEX IF NOT EXISTS idx_price_history_whisky_id ON price_history(whisky_id);

COMMIT;

-- 3) POST-CONDITIONS (assert before declaring success; else ROLLBACK)
PRAGMA integrity_check;                                       -- expected: ok
SELECT COUNT(*) FROM whiskies WHERE typeof(abv)='text';      -- expected: 0
SELECT COUNT(*) FROM whiskies WHERE abv<0 OR abv>100;        -- expected: 0
SELECT COUNT(*), MIN(abv), MAX(abv)
  FROM whiskies WHERE abv IS NOT NULL;                       -- expected: 1332, 39.9, 71.35
SELECT COUNT(*) FROM sqlite_master
  WHERE type='index' AND name IN
   ('idx_whiskies_distillery_id','idx_whiskies_name','idx_whiskies_country',
    'idx_tasting_notes_whisky_id','idx_flavor_profiles_whisky_id','idx_price_history_whisky_id');
                                                              -- expected: 6

-- 4) REVERSIBILITY: every change is undoable
--    ABV: re-import from source CSV OR restore from the pre-migration backup copy
--         (Rule 02: output/import/backups/production_p54_pre<ts>.db). The UPDATE is also
--         contained in the same transaction, so an error triggers ROLLBACK with zero change.
--    Indexes: DROP INDEX IF EXISTS idx_whiskies_distillery_id; ... (all 6) restores exactly.
"""

# ---------------------------------------------------------------------------
# BLOCKED items: each fails >=1 gate. SQL/approach provided for a FUTURE
# dedicated gated migration. DO NOT RUN in P54.
# ---------------------------------------------------------------------------
BLOCKED_REFERENCE = """-- ============================================================================
-- P54 BLOCKED REFERENCE  (DO NOT RUN in P54)
-- These items FAIL at least one of the 6 gates and are deferred to dedicated,
-- individually-gated migrations. Each block lists the failing gate(s) + reason.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- B1: Add PRIMARY KEY(whisky_id) to whiskies  [FAILS gate 1/5 comfort: forces full rebuild]
-- Root cause of P53's price_history FK mismatch (whisky_id has no PK/UNIQUE).
-- Evidence: whisky_id TEXT, 3293 distinct, 0 NULL, 0 dupes.
-- SQLite CANNOT ALTER TABLE ADD PRIMARY KEY -> requires CREATE TABLE AS SELECT rebuild of
-- the hottest table (3293 rows, joined by FastAPI on every whisky read).
-- Recommendation: ship as its own gated migration P55 with full backup + verify.
-- SAFE FUTURE SQL (reference only):
--   BEGIN;
--   CREATE TABLE whiskies_new (
--     whisky_id TEXT PRIMARY KEY,
--     name TEXT, original_name TEXT, distillery_id TEXT, country TEXT, region TEXT,
--     type TEXT, age REAL, age_statement TEXT, nas TEXT, abv REAL, bottle_size REAL,
--     cask_type TEXT, finish_type REAL, cask_strength TEXT, meta_critic_score REAL,
--     user_score REAL, data_confidence TEXT, completed_fields TEXT, notes_for_review TEXT,
--     brand TEXT
--   );
--   INSERT INTO whiskies_new SELECT * FROM whiskies;
--   DROP TABLE whiskies;
--   ALTER TABLE whiskies_new RENAME TO whiskies;
--   -- after this, price_history FK becomes valid; re-run PRAGMA foreign_key_check
--   COMMIT;
-- REVERSE: restore from pre-migration backup.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- B2: Fix distilleries mis-typed REAL columns (owner, parent_company, founded_year,
--     founder, status, location, coordinates, official_website, wikidata_id,
--     wikipedia_url, notes_for_review)  [FAILS gate 1: rebuild of 1823-row joined table]
-- Evidence: ALL 11 columns are 100% NULL (0 non-null values). Zero data to correct.
-- Benefit today = none; risk = full table rebuild of a FastAPI-read table.
-- Decision: DEFER. No data is corrupted (SQLite stores text correctly on read).
-- Revisit only if a writer starts pushing numeric-affinity-coerced values.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- B3: tasting_notes mis-typed REAL columns (source_url=109, source_name=77,
--     notes_for_review=1461 non-null TEXT actually stored)  [BLOCKED: rebuild of
--     FastAPI-read table; ship as own gated migration]
-- SAFE FUTURE SQL (reference only) - faithful rebuild preserving all columns:
--   BEGIN;
--   CREATE TABLE tasting_notes_new (
--     whisky_id TEXT, normalized_name TEXT, distillery_id TEXT,
--     source_url TEXT, source_name TEXT, data_confidence TEXT, notes_for_review TEXT,
--     nose_notes TEXT, palate_notes TEXT, finish_notes TEXT, aroma_tags TEXT,
--     source_system TEXT, source_doc TEXT, source_entry_number TEXT
--   );
--   INSERT INTO tasting_notes_new SELECT * FROM tasting_notes;
--   DROP TABLE tasting_notes;
--   ALTER TABLE tasting_notes_new RENAME TO tasting_notes;
--   COMMIT;
-- Note: must also add index idx_tasting_notes_whisky_id (already in GO block).
-- REVERSE: restore from pre-migration backup.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- B4: link-table id-type mismatch
--     (bottler_product_links.whisky_id, distillery_company_links.distillery_id,
--      whisky_product_entities.whisky_id/entity_id expect INTEGER; live keys are TEXT)
--   [FAILS gate: needs id-strategy decision; tables empty (0 rows) so no break now]
-- Evidence: all 3 link tables have 0 rows; no FK declared against them.
-- Decision: BLOCKED until the canonical id scheme (TEXT whisky_id vs INTEGER autoincrement)
-- is decided (backend uses TEXT keys; link tables assume INTEGER). Do not implement blindly.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- B5: price_history removal  [BLOCKED - see p54 + P53 price_history_usage_report.md]
-- Live: 1327 promoted rows, 1290 whiskies, 4 live API/code references, FK mismatch.
-- Decision: NO-GO. Decommission code first, then drop in its own gated migration.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- B6: flavor_profiles.production_price / production_rating (REAL, populated)
--   [BLOCKED - conflicts with Decision 1 (price excluded from product); needs design]
-- Decision: leave as-is; price-exclusion is a product rule, not a schema fix.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- NOTE: schema/schema.sql is a STALE legacy schema (countries, regions,
-- whisky_products, cask_types, flavor_tags) that does NOT exist in live production.db.
-- Do not apply it. Live tables are authoritative (whiskies, flavor_profiles,
-- knowledge_*, brands, bottlers, companies, ...). The prior memory/architecture.md
-- referencing the old 5-table model is also stale.
-- ---------------------------------------------------------------------------
"""

# ---------------------------------------------------------------------------
# Human-readable plan report
# ---------------------------------------------------------------------------
SCHEMA_PLAN = """# P54 Schema Modernization Plan

**Date:** 2026-07-12
**Phase:** Implementation (generate-only; no execution)
**Authoritative source:** live `output/import/production.db` (NOT `schema/schema.sql`, which is stale)
**Drift note:** Flutter uses a *separate* SQLite schema (`malt_radar_v2`, v6) and does not read production.db tables, so production.db DDL changes cannot break Flutter.

## Method (per AGENTS.md + AOS rules 01-08)
- Read-only inspection first; every finding backed by a SQL query.
- No `production.db` opened for writing; migration SQL only generated.
- Rule 02 discipline (backup + SHA256 + transaction + rollback + integrity/foreign_key check) is baked into the generated SQL comments.
- Changes are GO only if they pass **all 6 gates**: no prod risk, no Flutter break, no FastAPI break, no Drift break, fully reversible, covered by migration SQL.

## Inventory highlights (evidence)
| Fact | Value | Source query |
|---|---|---|
| whiskies rows / distinct whisky_id / NULL | 3293 / 3293 / 0 | `SELECT COUNT(*), COUNT(DISTINCT whisky_id), SUM(whisky_id IS NULL) FROM whiskies` |
| price_history FK mismatch | confirmed | `PRAGMA foreign_key_check` |
| abv stored as TEXT+'%' | 1314 | `SELECT COUNT(*) FROM whiskies WHERE typeof(abv)='text'` |
| abv stored as REAL (valid) | 18 | `SELECT COUNT(*) FROM whiskies WHERE typeof(abv)='real'` |
| distilleries mis-typed REAL-text cols non-null | 0 (all NULL) | per-column `COUNT(*) ... WHERE col IS NOT NULL` |
| tasting_notes mis-typed REAL-text cols non-null | 109/77/1461 | same, per column |
| link tables (bottler/distillery/entity) rows | 0 | `SELECT COUNT(*) FROM <t>` |
| FastAPI join key | `w.distillery_id = d.distillery_id` (both TEXT) | `backend/app/services/db_read_service.py:64,89` |

## GO changes (implemented in generated migration)
1. **G-A ABV normalization** — `UPDATE whiskies SET abv = CAST(REPLACE(REPLACE(abv,',','.'),'%','') AS REAL) WHERE typeof(abv)='text' AND abv LIKE '%'`.
   - Passes all gates: pure UPDATE, no DDL, no code contract change, reversible (backup + in-tx rollback), verified in P53 (1,314 -> 0 text, 0 out-of-range, range 39.9-71.35).
2. **G-B Missing indexes** — on `whiskies(distillery_id, name, country)`, `tasting_notes(whisky_id)`, `flavor_profiles(whisky_id)`, `price_history(whisky_id)`.
   - Passes all gates: query-plan only, fully reversible via DROP INDEX, no semantic change, no code break.

## BLOCKED changes (deferred, with reference SQL in p54_blocked_reference.sql)
- **B1** whisky_id PRIMARY KEY — forces full table rebuild of hottest table → own gated migration P55.
- **B2** distilleries mis-typed columns — 100% NULL, zero benefit, rebuild risk → defer.
- **B3** tasting_notes mis-typed columns — rebuild of FastAPI-read table → own gated migration.
- **B4** link-table id-type mismatch — needs id-strategy decision; tables empty → no break now.
- **B5** price_history removal — live data + live code refs (P53 NO-GO).
- **B6** flavor_profiles price columns — product-rule conflict (Decision 1).

## Deliverables
- `output/migrations/p54_go_migration.sql` — the only SQL intended to run (after human review, on staging).
- `output/migrations/p54_blocked_reference.sql` — reference SQL for deferred items (DO NOT RUN).
- `output/reports/p54_migration_preview.sql` — copy of GO migration for review.
- `output/reports/p54_schema_plan.md` — this file.
- `output/reports/p54_blocked_changes.md` — blocked items with gate-failure reasoning.
- `scripts/p54_schema_modernization.py` — deterministic generator (no DB, no execution).

## Verification status
SQL was NOT executed. Ad-hoc verification (separate, rolled-back) confirmed the GO block parses and is reversible on a staging copy without mutation. See p54_blocked_changes.md footer.
"""

BLOCKED_REPORT = """# P54 Blocked Changes

Every item below FAILS at least one of the 6 implementation gates and is **not** implemented in P54.
Each carries reference SQL for a future dedicated, gated migration. None of this file is executed.

## B1 — `whiskies.whisky_id` PRIMARY KEY
- **Failing gate:** 1 (production risk comfort) / 5 (reversibility effort). Adding a PK in SQLite requires a full `CREATE TABLE AS SELECT` rebuild of the 3,293-row hottest table.
- **Why it matters:** it is the root cause of the `price_history` FK mismatch (P53).
- **Evidence:** `whisky_id` TEXT, 3293 distinct, 0 NULL, 0 dupes → safe *content*, but the *operation* is a structural rebuild.
- **Disposition:** defer to a dedicated gated migration (P55) with full backup + `PRAGMA foreign_key_check` after.
- **Reference SQL:** in `p54_blocked_reference.sql` (rebuild + rename).

## B2 — `distilleries` mis-typed REAL columns
- **Failing gate:** 1. 11 columns declared REAL but semantically text (`owner`, `founded_year`, ...).
- **Evidence:** **all 11 are 100% NULL** (0 non-null). There is nothing to correct; SQLite already stores/returns text correctly on read.
- **Disposition:** defer. Zero current benefit, non-zero rebuild risk of a FastAPI-joined table.

## B3 — `tasting_notes` mis-typed REAL columns
- **Failing gate:** 1/5. `source_url`(109), `source_name`(77), `notes_for_review`(1461) hold TEXT in REAL-typed columns.
- **Evidence:** real TEXT data exists → a rebuild must preserve it faithfully.
- **Disposition:** ship as its own gated migration (rebuild + rename, add `idx_tasting_notes_whisky_id`).
- **Reference SQL:** in `p54_blocked_reference.sql`.

## B4 — Link-table id-type mismatch
- **Failing gate:** design/consensus. `bottler_product_links.whisky_id`, `distillery_company_links.distillery_id`, `whisky_product_entities.*` expect INTEGER; live keys (`whiskies.whisky_id`, `distilleries.distillery_id`) are TEXT.
- **Evidence:** all 3 link tables have **0 rows**; no FK references them today → no active breakage.
- **Disposition:** BLOCKED until the canonical id scheme (TEXT vs INTEGER autoincrement) is decided. Do not implement speculatively.

## B5 — `price_history` removal
- **Failing gate:** 2/3 (live code) + data loss risk. 1,327 promoted rows, 1,290 whiskies, 4 live API/code references.
- **Disposition:** NO-GO (see `price_history_usage_report.md` from P53). Decommission code first.

## B6 — `flavor_profiles.production_price` / `production_rating`
- **Failing gate:** product-rule (Decision 1: price excluded). Changing schema here risks violating the price-exclusion rule.
- **Disposition:** leave as-is; not a schema-defect fix.

## Stale-schema note
`schema/schema.sql` and `memory/architecture.md` describe a legacy 5-table model (`countries`, `whisky_products`, `cask_types`, ...) that **does not exist** in the live DB. The live schema is authoritative. Do not apply the legacy DDL.

## Ad-hoc verification of the GO block (not "suite green")
A separate temporary script ran the GO SQL against a staging copy **inside BEGIN/ROLLBACK**, asserting:
- 1,314 abv rows normalized; 0 text rows remain; 0 abv outside 0..100; corrected range 39.9-71.35.
- 6 indexes present after; `PRAGMA integrity_check` = ok.
- After ROLLBACK: staging untouched (1,314 text-abv rows, 1,327 price_history rows intact).
Result: PASS, non-destructive. No production/staging data persisted. The migration remains **proposed, not executed**.
"""


def main():
    # write migration files
    p_go = os.path.join(MIG_DIR, "p54_go_migration.sql")
    p_blocked = os.path.join(MIG_DIR, "p54_blocked_reference.sql")
    p_preview = os.path.join(REP_DIR, "p54_migration_preview.sql")
    p_plan = os.path.join(REP_DIR, "p54_schema_plan.md")
    p_blocked_rep = os.path.join(REP_DIR, "p54_blocked_changes.md")

    with open(p_go, "w", encoding="utf-8") as f:
        f.write(GO_MIGRATION.strip() + "\n")
    with open(p_blocked, "w", encoding="utf-8") as f:
        f.write(BLOCKED_REFERENCE.strip() + "\n")
    with open(p_preview, "w", encoding="utf-8") as f:
        f.write(GO_MIGRATION.strip() + "\n")
    with open(p_plan, "w", encoding="utf-8") as f:
        f.write(SCHEMA_PLAN.strip() + "\n")
    with open(p_blocked_rep, "w", encoding="utf-8") as f:
        f.write(BLOCKED_REPORT.strip() + "\n")

    print("P54 generated (NO execution):")
    for p in (p_go, p_blocked, p_preview, p_plan, p_blocked_rep):
        print("  wrote", os.path.relpath(p, ROOT))
    print("\nGO items: G-A abv normalize, G-B indexes (6).")
    print("BLOCKED items: B1..B6 (deferred, reference SQL provided).")
    print("Rule honored: production.db never opened; no SQL executed.")


if __name__ == "__main__":
    main()
